# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YjEzMzAwYzIzNmY5NzQ3NjlhYThkZDE3MDRlZGJmYmE5NGJlNjI4OTkwMjgxMTUwNDJmYmRiZDQ1YzNiMWVlM2UzZjgzMmQ5MmNmY2QxODRjMmIzYWZmYTc4OTg2ZmIzNjhhZDY1ZGNkNTIzYWE5N2YxNWY3MmQ1YjI2ODhjNmY=
