package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlerteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteAllPropertiesEquals(Alerte expected, Alerte actual) {
        assertAlerteAutoGeneratedPropertiesEquals(expected, actual);
        assertAlerteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteAllUpdatablePropertiesEquals(Alerte expected, Alerte actual) {
        assertAlerteUpdatableFieldsEquals(expected, actual);
        assertAlerteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteAutoGeneratedPropertiesEquals(Alerte expected, Alerte actual) {
        assertThat(actual)
            .as("Verify Alerte auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteUpdatableFieldsEquals(Alerte expected, Alerte actual) {
        assertThat(actual)
            .as("Verify Alerte relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getContenu()).as("check contenu").isEqualTo(expected.getContenu()))
            .satisfies(a -> assertThat(a.getTypeAnnonce()).as("check typeAnnonce").isEqualTo(expected.getTypeAnnonce()))
            .satisfies(a -> assertThat(a.getPrixMin()).as("check prixMin").isEqualTo(expected.getPrixMin()))
            .satisfies(a -> assertThat(a.getPrixMax()).as("check prixMax").isEqualTo(expected.getPrixMax()))
            .satisfies(a -> assertThat(a.getSurfaceMin()).as("check surfaceMin").isEqualTo(expected.getSurfaceMin()))
            .satisfies(a -> assertThat(a.getNombreChambresMin()).as("check nombreChambresMin").isEqualTo(expected.getNombreChambresMin()))
            .satisfies(a -> assertThat(a.getMeubleUniquement()).as("check meubleUniquement").isEqualTo(expected.getMeubleUniquement()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getFrequence()).as("check frequence").isEqualTo(expected.getFrequence()))
            .satisfies(a -> assertThat(a.getDerniereExecution()).as("check derniereExecution").isEqualTo(expected.getDerniereExecution()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteUpdatableRelationshipsEquals(Alerte expected, Alerte actual) {
        assertThat(actual)
            .as("Verify Alerte relationships")
            .satisfies(a -> assertThat(a.getLocalite()).as("check localite").isEqualTo(expected.getLocalite()))
            .satisfies(a -> assertThat(a.getQuartier()).as("check quartier").isEqualTo(expected.getQuartier()))
            .satisfies(a -> assertThat(a.getTypeImmobilier()).as("check typeImmobilier").isEqualTo(expected.getTypeImmobilier()));
    }
}
