package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlerteNotifieeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteNotifieeAllPropertiesEquals(AlerteNotifiee expected, AlerteNotifiee actual) {
        assertAlerteNotifieeAutoGeneratedPropertiesEquals(expected, actual);
        assertAlerteNotifieeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteNotifieeAllUpdatablePropertiesEquals(AlerteNotifiee expected, AlerteNotifiee actual) {
        assertAlerteNotifieeUpdatableFieldsEquals(expected, actual);
        assertAlerteNotifieeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteNotifieeAutoGeneratedPropertiesEquals(AlerteNotifiee expected, AlerteNotifiee actual) {
        assertThat(actual)
            .as("Verify AlerteNotifiee auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteNotifieeUpdatableFieldsEquals(AlerteNotifiee expected, AlerteNotifiee actual) {
        assertThat(actual)
            .as("Verify AlerteNotifiee relevant properties")
            .satisfies(a -> assertThat(a.getDateEnvoi()).as("check dateEnvoi").isEqualTo(expected.getDateEnvoi()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteNotifieeUpdatableRelationshipsEquals(AlerteNotifiee expected, AlerteNotifiee actual) {
        assertThat(actual)
            .as("Verify AlerteNotifiee relationships")
            .satisfies(a -> assertThat(a.getAlerte()).as("check alerte").isEqualTo(expected.getAlerte()))
            .satisfies(a -> assertThat(a.getAnnonce()).as("check annonce").isEqualTo(expected.getAnnonce()));
    }
}
