package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnnonceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnnonceAllPropertiesEquals(Annonce expected, Annonce actual) {
        assertAnnonceAutoGeneratedPropertiesEquals(expected, actual);
        assertAnnonceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnnonceAllUpdatablePropertiesEquals(Annonce expected, Annonce actual) {
        assertAnnonceUpdatableFieldsEquals(expected, actual);
        assertAnnonceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnnonceAutoGeneratedPropertiesEquals(Annonce expected, Annonce actual) {
        assertThat(actual)
            .as("Verify Annonce auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnnonceUpdatableFieldsEquals(Annonce expected, Annonce actual) {
        assertThat(actual)
            .as("Verify Annonce relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getContenu()).as("check contenu").isEqualTo(expected.getContenu()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getPrix()).as("check prix").isEqualTo(expected.getPrix()))
            .satisfies(a -> assertThat(a.getNombreVues()).as("check nombreVues").isEqualTo(expected.getNombreVues()))
            .satisfies(a -> assertThat(a.getDatePublication()).as("check datePublication").isEqualTo(expected.getDatePublication()))
            .satisfies(a -> assertThat(a.getDateExpiration()).as("check dateExpiration").isEqualTo(expected.getDateExpiration()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnnonceUpdatableRelationshipsEquals(Annonce expected, Annonce actual) {
        assertThat(actual)
            .as("Verify Annonce relationships")
            .satisfies(a -> assertThat(a.getImmobilier()).as("check immobilier").isEqualTo(expected.getImmobilier()));
    }
}
