package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DetailColocationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailColocationAllPropertiesEquals(DetailColocation expected, DetailColocation actual) {
        assertDetailColocationAutoGeneratedPropertiesEquals(expected, actual);
        assertDetailColocationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailColocationAllUpdatablePropertiesEquals(DetailColocation expected, DetailColocation actual) {
        assertDetailColocationUpdatableFieldsEquals(expected, actual);
        assertDetailColocationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailColocationAutoGeneratedPropertiesEquals(DetailColocation expected, DetailColocation actual) {
        assertThat(actual)
            .as("Verify DetailColocation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailColocationUpdatableFieldsEquals(DetailColocation expected, DetailColocation actual) {
        assertThat(actual)
            .as("Verify DetailColocation relevant properties")
            .satisfies(a -> assertThat(a.getNombrePlaces()).as("check nombrePlaces").isEqualTo(expected.getNombrePlaces()))
            .satisfies(a -> assertThat(a.getPlacesRestantes()).as("check placesRestantes").isEqualTo(expected.getPlacesRestantes()))
            .satisfies(a -> assertThat(a.getSexeRecherche()).as("check sexeRecherche").isEqualTo(expected.getSexeRecherche()))
            .satisfies(a -> assertThat(a.getAgeMin()).as("check ageMin").isEqualTo(expected.getAgeMin()))
            .satisfies(a -> assertThat(a.getAgeMax()).as("check ageMax").isEqualTo(expected.getAgeMax()))
            .satisfies(a -> assertThat(a.getLoyer()).as("check loyer").isEqualTo(expected.getLoyer()))
            .satisfies(a -> assertThat(a.getCaution()).as("check caution").isEqualTo(expected.getCaution()))
            .satisfies(a -> assertThat(a.getCharges()).as("check charges").isEqualTo(expected.getCharges()))
            .satisfies(a -> assertThat(a.getReglesDeVie()).as("check reglesDeVie").isEqualTo(expected.getReglesDeVie()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetailColocationUpdatableRelationshipsEquals(DetailColocation expected, DetailColocation actual) {
        assertThat(actual)
            .as("Verify DetailColocation relationships")
            .satisfies(a -> assertThat(a.getAnnonce()).as("check annonce").isEqualTo(expected.getAnnonce()))
            .satisfies(a -> assertThat(a.getEquipementses()).as("check equipementses").isEqualTo(expected.getEquipementses()));
    }
}
