package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EquipementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipementAllPropertiesEquals(Equipement expected, Equipement actual) {
        assertEquipementAutoGeneratedPropertiesEquals(expected, actual);
        assertEquipementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipementAllUpdatablePropertiesEquals(Equipement expected, Equipement actual) {
        assertEquipementUpdatableFieldsEquals(expected, actual);
        assertEquipementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipementAutoGeneratedPropertiesEquals(Equipement expected, Equipement actual) {
        assertThat(actual)
            .as("Verify Equipement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipementUpdatableFieldsEquals(Equipement expected, Equipement actual) {
        assertThat(actual)
            .as("Verify Equipement relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getIcone()).as("check icone").isEqualTo(expected.getIcone()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipementUpdatableRelationshipsEquals(Equipement expected, Equipement actual) {
        assertThat(actual)
            .as("Verify Equipement relationships")
            .satisfies(a -> assertThat(a.getColocationses()).as("check colocationses").isEqualTo(expected.getColocationses()));
    }
}
