package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FavoriAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriAllPropertiesEquals(Favori expected, Favori actual) {
        assertFavoriAutoGeneratedPropertiesEquals(expected, actual);
        assertFavoriAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriAllUpdatablePropertiesEquals(Favori expected, Favori actual) {
        assertFavoriUpdatableFieldsEquals(expected, actual);
        assertFavoriUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriAutoGeneratedPropertiesEquals(Favori expected, Favori actual) {
        assertThat(actual)
            .as("Verify Favori auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriUpdatableFieldsEquals(Favori expected, Favori actual) {
        assertThat(actual)
            .as("Verify Favori relevant properties")
            .satisfies(a -> assertThat(a.getDateAjout()).as("check dateAjout").isEqualTo(expected.getDateAjout()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriUpdatableRelationshipsEquals(Favori expected, Favori actual) {
        assertThat(actual)
            .as("Verify Favori relationships")
            .satisfies(a -> assertThat(a.getAnnonce()).as("check annonce").isEqualTo(expected.getAnnonce()));
    }
}
