package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageAllPropertiesEquals(Image expected, Image actual) {
        assertImageAutoGeneratedPropertiesEquals(expected, actual);
        assertImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageAllUpdatablePropertiesEquals(Image expected, Image actual) {
        assertImageUpdatableFieldsEquals(expected, actual);
        assertImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageAutoGeneratedPropertiesEquals(Image expected, Image actual) {
        assertThat(actual)
            .as("Verify Image auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageUpdatableFieldsEquals(Image expected, Image actual) {
        assertThat(actual)
            .as("Verify Image relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getOrdre()).as("check ordre").isEqualTo(expected.getOrdre()))
            .satisfies(a -> assertThat(a.getPrincipale()).as("check principale").isEqualTo(expected.getPrincipale()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageUpdatableRelationshipsEquals(Image expected, Image actual) {
        assertThat(actual)
            .as("Verify Image relationships")
            .satisfies(a -> assertThat(a.getImmobilier()).as("check immobilier").isEqualTo(expected.getImmobilier()));
    }
}
