package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImmobilierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImmobilierAllPropertiesEquals(Immobilier expected, Immobilier actual) {
        assertImmobilierAutoGeneratedPropertiesEquals(expected, actual);
        assertImmobilierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImmobilierAllUpdatablePropertiesEquals(Immobilier expected, Immobilier actual) {
        assertImmobilierUpdatableFieldsEquals(expected, actual);
        assertImmobilierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImmobilierAutoGeneratedPropertiesEquals(Immobilier expected, Immobilier actual) {
        assertThat(actual)
            .as("Verify Immobilier auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImmobilierUpdatableFieldsEquals(Immobilier expected, Immobilier actual) {
        assertThat(actual)
            .as("Verify Immobilier relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getAdresse()).as("check adresse").isEqualTo(expected.getAdresse()))
            .satisfies(a -> assertThat(a.getSurface()).as("check surface").isEqualTo(expected.getSurface()))
            .satisfies(a -> assertThat(a.getNombrePieces()).as("check nombrePieces").isEqualTo(expected.getNombrePieces()))
            .satisfies(a -> assertThat(a.getNombreChambres()).as("check nombreChambres").isEqualTo(expected.getNombreChambres()))
            .satisfies(a -> assertThat(a.getNombreSallesBain()).as("check nombreSallesBain").isEqualTo(expected.getNombreSallesBain()))
            .satisfies(a -> assertThat(a.getNombreSalons()).as("check nombreSalons").isEqualTo(expected.getNombreSalons()))
            .satisfies(a -> assertThat(a.getGarage()).as("check garage").isEqualTo(expected.getGarage()))
            .satisfies(a -> assertThat(a.getPiscine()).as("check piscine").isEqualTo(expected.getPiscine()))
            .satisfies(a -> assertThat(a.getMeuble()).as("check meuble").isEqualTo(expected.getMeuble()))
            .satisfies(a -> assertThat(a.getDisponibleA()).as("check disponibleA").isEqualTo(expected.getDisponibleA()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImmobilierUpdatableRelationshipsEquals(Immobilier expected, Immobilier actual) {
        assertThat(actual)
            .as("Verify Immobilier relationships")
            .satisfies(a -> assertThat(a.getLocalite()).as("check localite").isEqualTo(expected.getLocalite()))
            .satisfies(a -> assertThat(a.getQuartier()).as("check quartier").isEqualTo(expected.getQuartier()))
            .satisfies(a -> assertThat(a.getTypeImmobilier()).as("check typeImmobilier").isEqualTo(expected.getTypeImmobilier()));
    }
}
