package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LocaliteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocaliteAllPropertiesEquals(Localite expected, Localite actual) {
        assertLocaliteAutoGeneratedPropertiesEquals(expected, actual);
        assertLocaliteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocaliteAllUpdatablePropertiesEquals(Localite expected, Localite actual) {
        assertLocaliteUpdatableFieldsEquals(expected, actual);
        assertLocaliteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocaliteAutoGeneratedPropertiesEquals(Localite expected, Localite actual) {
        assertThat(actual)
            .as("Verify Localite auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocaliteUpdatableFieldsEquals(Localite expected, Localite actual) {
        assertThat(actual)
            .as("Verify Localite relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocaliteUpdatableRelationshipsEquals(Localite expected, Localite actual) {
        // empty method
    }
}
