package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PrixAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrixAllPropertiesEquals(Prix expected, Prix actual) {
        assertPrixAutoGeneratedPropertiesEquals(expected, actual);
        assertPrixAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrixAllUpdatablePropertiesEquals(Prix expected, Prix actual) {
        assertPrixUpdatableFieldsEquals(expected, actual);
        assertPrixUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrixAutoGeneratedPropertiesEquals(Prix expected, Prix actual) {
        assertThat(actual)
            .as("Verify Prix auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrixUpdatableFieldsEquals(Prix expected, Prix actual) {
        assertThat(actual)
            .as("Verify Prix relevant properties")
            .satisfies(a -> assertThat(a.getPrix()).as("check prix").isEqualTo(expected.getPrix()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCharges()).as("check charges").isEqualTo(expected.getCharges()))
            .satisfies(a -> assertThat(a.getPeriodicite()).as("check periodicite").isEqualTo(expected.getPeriodicite()))
            .satisfies(a -> assertThat(a.getDateEffet()).as("check dateEffet").isEqualTo(expected.getDateEffet()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrixUpdatableRelationshipsEquals(Prix expected, Prix actual) {
        assertThat(actual)
            .as("Verify Prix relationships")
            .satisfies(a -> assertThat(a.getImmobilier()).as("check immobilier").isEqualTo(expected.getImmobilier()));
    }
}
