package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfilDemarcheurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilDemarcheurAllPropertiesEquals(ProfilDemarcheur expected, ProfilDemarcheur actual) {
        assertProfilDemarcheurAutoGeneratedPropertiesEquals(expected, actual);
        assertProfilDemarcheurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilDemarcheurAllUpdatablePropertiesEquals(ProfilDemarcheur expected, ProfilDemarcheur actual) {
        assertProfilDemarcheurUpdatableFieldsEquals(expected, actual);
        assertProfilDemarcheurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilDemarcheurAutoGeneratedPropertiesEquals(ProfilDemarcheur expected, ProfilDemarcheur actual) {
        assertThat(actual)
            .as("Verify ProfilDemarcheur auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilDemarcheurUpdatableFieldsEquals(ProfilDemarcheur expected, ProfilDemarcheur actual) {
        assertThat(actual)
            .as("Verify ProfilDemarcheur relevant properties")
            .satisfies(a -> assertThat(a.getStatutValidation()).as("check statutValidation").isEqualTo(expected.getStatutValidation()))
            .satisfies(a -> assertThat(a.getDateValidation()).as("check dateValidation").isEqualTo(expected.getDateValidation()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilDemarcheurUpdatableRelationshipsEquals(ProfilDemarcheur expected, ProfilDemarcheur actual) {
        // empty method
    }
}
