package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfilProprietaireAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilProprietaireAllPropertiesEquals(ProfilProprietaire expected, ProfilProprietaire actual) {
        assertProfilProprietaireAutoGeneratedPropertiesEquals(expected, actual);
        assertProfilProprietaireAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilProprietaireAllUpdatablePropertiesEquals(ProfilProprietaire expected, ProfilProprietaire actual) {
        assertProfilProprietaireUpdatableFieldsEquals(expected, actual);
        assertProfilProprietaireUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilProprietaireAutoGeneratedPropertiesEquals(ProfilProprietaire expected, ProfilProprietaire actual) {
        assertThat(actual)
            .as("Verify ProfilProprietaire auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilProprietaireUpdatableFieldsEquals(ProfilProprietaire expected, ProfilProprietaire actual) {
        assertThat(actual)
            .as("Verify ProfilProprietaire relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getRaisonSociale()).as("check raisonSociale").isEqualTo(expected.getRaisonSociale()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilProprietaireUpdatableRelationshipsEquals(ProfilProprietaire expected, ProfilProprietaire actual) {
        // empty method
    }
}
