package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QuartierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuartierAllPropertiesEquals(Quartier expected, Quartier actual) {
        assertQuartierAutoGeneratedPropertiesEquals(expected, actual);
        assertQuartierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuartierAllUpdatablePropertiesEquals(Quartier expected, Quartier actual) {
        assertQuartierUpdatableFieldsEquals(expected, actual);
        assertQuartierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuartierAutoGeneratedPropertiesEquals(Quartier expected, Quartier actual) {
        assertThat(actual)
            .as("Verify Quartier auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuartierUpdatableFieldsEquals(Quartier expected, Quartier actual) {
        assertThat(actual)
            .as("Verify Quartier relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuartierUpdatableRelationshipsEquals(Quartier expected, Quartier actual) {
        assertThat(actual)
            .as("Verify Quartier relationships")
            .satisfies(a -> assertThat(a.getLocalite()).as("check localite").isEqualTo(expected.getLocalite()));
    }
}
