package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeImmobilierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeImmobilierAllPropertiesEquals(TypeImmobilier expected, TypeImmobilier actual) {
        assertTypeImmobilierAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeImmobilierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeImmobilierAllUpdatablePropertiesEquals(TypeImmobilier expected, TypeImmobilier actual) {
        assertTypeImmobilierUpdatableFieldsEquals(expected, actual);
        assertTypeImmobilierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeImmobilierAutoGeneratedPropertiesEquals(TypeImmobilier expected, TypeImmobilier actual) {
        assertThat(actual)
            .as("Verify TypeImmobilier auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeImmobilierUpdatableFieldsEquals(TypeImmobilier expected, TypeImmobilier actual) {
        assertThat(actual)
            .as("Verify TypeImmobilier relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeImmobilierUpdatableRelationshipsEquals(TypeImmobilier expected, TypeImmobilier actual) {
        // empty method
    }
}
