package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDocumentAllPropertiesEquals(TypeDocument expected, TypeDocument actual) {
        assertTypeDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDocumentAllUpdatablePropertiesEquals(TypeDocument expected, TypeDocument actual) {
        assertTypeDocumentUpdatableFieldsEquals(expected, actual);
        assertTypeDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDocumentAutoGeneratedPropertiesEquals(TypeDocument expected, TypeDocument actual) {
        assertThat(actual)
            .as("Verify TypeDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDocumentUpdatableFieldsEquals(TypeDocument expected, TypeDocument actual) {
        assertThat(actual)
            .as("Verify TypeDocument relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDocumentUpdatableRelationshipsEquals(TypeDocument expected, TypeDocument actual) {
        // empty method
    }
}
