package bf.colocation.immo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VueAnnonceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVueAnnonceAllPropertiesEquals(VueAnnonce expected, VueAnnonce actual) {
        assertVueAnnonceAutoGeneratedPropertiesEquals(expected, actual);
        assertVueAnnonceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVueAnnonceAllUpdatablePropertiesEquals(VueAnnonce expected, VueAnnonce actual) {
        assertVueAnnonceUpdatableFieldsEquals(expected, actual);
        assertVueAnnonceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVueAnnonceAutoGeneratedPropertiesEquals(VueAnnonce expected, VueAnnonce actual) {
        assertThat(actual)
            .as("Verify VueAnnonce auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVueAnnonceUpdatableFieldsEquals(VueAnnonce expected, VueAnnonce actual) {
        assertThat(actual)
            .as("Verify VueAnnonce relevant properties")
            .satisfies(a -> assertThat(a.getDateVue()).as("check dateVue").isEqualTo(expected.getDateVue()))
            .satisfies(a -> assertThat(a.getAdresseIp()).as("check adresseIp").isEqualTo(expected.getAdresseIp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVueAnnonceUpdatableRelationshipsEquals(VueAnnonce expected, VueAnnonce actual) {
        assertThat(actual)
            .as("Verify VueAnnonce relationships")
            .satisfies(a -> assertThat(a.getAnnonce()).as("check annonce").isEqualTo(expected.getAnnonce()));
    }
}
